ALTER TABLE `ali_oss_file`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `knowledge_chunk`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT,
  MODIFY COLUMN `file_id` BIGINT NOT NULL COMMENT '知识库文件ID';

ALTER TABLE `log_info`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `sensitive_word`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `word_frequency`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `sensitive_category`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE `sensitive_audit_log`
  MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT;
